// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjos4QsthyGLqHE_rGOK_c8_nZr5sChE',
    appId: '1:912542896591:web:5d2ced3f3291ab191dc2ba',
    messagingSenderId: '912542896591',
    projectId: 'diario-aventuras-6db45',
    authDomain: 'diario-aventuras-6db45.firebaseapp.com',
    storageBucket: 'diario-aventuras-6db45.firebasestorage.app',
    measurementId: 'G-9JXFJMQYTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdLTM-70XlcmiOO336v7263WTwYgprm8',
    appId: '1:912542896591:android:f5f53a11ebfe046e1dc2ba',
    messagingSenderId: '912542896591',
    projectId: 'diario-aventuras-6db45',
    storageBucket: 'diario-aventuras-6db45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnpAgTkRJGpBhBPf4tyuPWAwmdmwZ_lQE',
    appId: '1:912542896591:ios:f60df1ffa666510d1dc2ba',
    messagingSenderId: '912542896591',
    projectId: 'diario-aventuras-6db45',
    storageBucket: 'diario-aventuras-6db45.firebasestorage.app',
    iosBundleId: 'com.example.diarioAventuras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnpAgTkRJGpBhBPf4tyuPWAwmdmwZ_lQE',
    appId: '1:912542896591:ios:f60df1ffa666510d1dc2ba',
    messagingSenderId: '912542896591',
    projectId: 'diario-aventuras-6db45',
    storageBucket: 'diario-aventuras-6db45.firebasestorage.app',
    iosBundleId: 'com.example.diarioAventuras',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjos4QsthyGLqHE_rGOK_c8_nZr5sChE',
    appId: '1:912542896591:web:fd799b9979379cf71dc2ba',
    messagingSenderId: '912542896591',
    projectId: 'diario-aventuras-6db45',
    authDomain: 'diario-aventuras-6db45.firebaseapp.com',
    storageBucket: 'diario-aventuras-6db45.firebasestorage.app',
    measurementId: 'G-BCK3QTRN12',
  );
}
